#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BraspagHackathon.TimeZado.Resource", IsApplication=true)]

namespace BraspagHackathon.TimeZado
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BraspagHackathon.TimeZado.Model.Resource.String.ApplicationName = global::BraspagHackathon.TimeZado.Resource.String.ApplicationName;
			global::BraspagHackathon.TimeZado.Model.Resource.String.Hello = global::BraspagHackathon.TimeZado.Resource.String.Hello;
			global::BraspagHackaton.TimeZado.Services.Resource.String.ApplicationName = global::BraspagHackathon.TimeZado.Resource.String.ApplicationName;
			global::BraspagHackaton.TimeZado.Services.Resource.String.Hello = global::BraspagHackathon.TimeZado.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int edittext_bottom_line = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050013
			public const int Address = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int CardNumber = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int CardsList = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int CreateCustomerButton = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int Cvv = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int FirstName = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int Holder = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int InsertCardButton = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int LastName = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int Location = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int MerchantInfo_Address = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int MerchantInfo_Description = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int MerchantInfo_Name = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int MerchantInfo_Site = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int NearbyMerchantsList = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int OfferInfo_Description = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int OfferInfo_Image = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int OfferInfo_Name = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int OfferInfo_Price = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int OffersList = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int OpenInsertCardWindowButton = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int OpenManageCardButton = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int OpenNearbyMerchantsButton = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int ValidThru = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CardsListTemplate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FirstAccessConfiguration = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int InsertCardWindow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ManageCard = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MerchantOffers = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MerchantsListTemplate = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NearbyMerchants = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OfferListTemplate = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int InsertNewCard = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int OpenManageCard = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
